name: Publish Custom App

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  publish:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set tag variable as an output
        id: vars
        run: 
          |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Show the tag variable
        run: 
          |
          echo "found tag new: ${{ steps.vars.outputs.tag }}"

      - name: Validate tag
        run:
          |
          python .github/workflows/tag_validator.py ${{ steps.vars.outputs.tag }}
