name: Publish Custom App

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  publish_testapp:
    runs-on: macos-13
    environment: ${{ contains(github.ref, 'testapp') && 'testapp' || 'internal' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show the full github ref value
        run:
         |
         echo "${GITHUB_REF}"

      - name: Show the pattern matched ref value
        run:
         |
         echo ${GITHUB_REF#refs/*/}
      
      - name: Set tag variable as an output
        id: vars
        run: 
          |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Show the tag variable
        run: 
          |
          echo "found new tag: ${{ steps.vars.outputs.tag }}"

      - name: Validate tag
        run:
          |
          python .github/workflows/tag_validator.py ${{ steps.vars.outputs.tag }}

      - name: Show which environment it is
        env:
            ENV_NAME: ${{ vars.ENV_NAME }}
        run:
          | 
          echo "the current environment is: ${{ vars.ENV_NAME }}"
