name: Publish Custom App

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  publish:
    runs-on: macos-13
    environment: 
        name: internal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show the full github ref value
        run:
         |
         echo "${GITHUB_REF}"
      
      - name: Set tag variable as an output
        id: vars
        run: 
          |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Show the tag variable
        run: 
          |
          echo "found new tag: ${{ steps.vars.outputs.tag }}"

      - name: Validate tag
        run:
          |
          python .github/workflows/tag_validator.py ${{ steps.vars.outputs.tag }}

      - name: Show which environment it is
        run:
          | 
          echo "the current environment is: ${{ env.ENV_NAME }}"
